#!/bin/sh
export APP_STUB_VERSION=3.0.4
export ORANGE_VERSION=1.3.0
export CEYLON_VERSION=1.3.3
LAUNCH4J_MAJOR=3
LAUNCH4J_MINOR=12
export LAUNCH4J_VERSION=${LAUNCH4J_MAJOR}.${LAUNCH4J_MINOR}
export JARBUNDLER_VERSION=3.3.0
