package controller.map.simplexml.node;

import util.EqualsAny;
import model.map.PlayerCollection;
import model.map.fixtures.Grove;
import controller.map.SPFormatException;

/**
 * A Node to produce a Grove.
 * @author Jonathan Lovelace
 */
public class GroveNode extends AbstractFixtureNode<Grove> {
	/**
	 * Constructor.
	 */
	public GroveNode() {
		super(Grove.class);
	}
	/**
	 * @param players ignored
	 * @return the Grove this represents
	 * @throws SPFormatException if missing a required property that should be generated by the factory
	 */
	@Override
	public Grove produce(final PlayerCollection players) throws SPFormatException {
		return new Grove("orchard".equals(getProperty("tag")),
				Boolean.parseBoolean(getProperty("wild")), getProperty("tree"));
	}
	/**
	 * @param property the name of a property
	 * @return whether this kind of node can use the property
	 */
	@Override
	public boolean canUse(final String property) {
		return EqualsAny.equalsAny(property, "tag", "wild", "tree");
	}
	/**
	 * Check whether the Node's data is valid. A Grove is valid if it has no
	 * children and "tag" (should be generated by the factory, not in the XML),
	 * "wild", and "tree" properties.
	 * @throws SPFormatException if the data is invalid
	 */
	@Override
	public void checkNode() throws SPFormatException {
		if (iterator().hasNext()) {
			throw new SPFormatException(
					"Groves and orchards shouldn't have children", getLine());
		} else if (hasProperty("tag")) {
			if (!hasProperty("wild") || !hasProperty("tree")) {
				throw new SPFormatException(
						"Groves and orchards must have \"wild\" and \"tree\" properties",
						getLine());
			}
		} else {
			throw new SPFormatException(
					"The NodeFactory should have generated a \"tag\" property to tell whether this is a grove or an orchard",
					getLine());
		}
	}
	/**
	 * @return a String representation of the node
	 */
	@Override
	public String toString() {
		return "GroveNode";
	}
}
