package controller.map.simplexml.node;

import model.map.PlayerCollection;
import model.map.fixtures.Grove;
import util.EqualsAny;
import util.Warning;
import controller.map.DeprecatedPropertyException;
import controller.map.MissingParameterException;
import controller.map.SPFormatException;
import controller.map.UnwantedChildException;
import controller.map.misc.IDFactory;

/**
 * A Node to produce a Grove.
 * @author Jonathan Lovelace
 */
@Deprecated
public class GroveNode extends AbstractFixtureNode<Grove> {
	/**
	 * The former, deprecated, name of the parameter telling what kind of trees.
	 */
	private static final String OLD_KIND_PARAM = "tree";
	/**
	 * The name of the parameter telling whether this is a wild grove or orchard or a cultivated one.
	 */
	private static final String WILD_PARAM = "wild";
	/**
	 * The name of the parameter (generated by the factory) that tells us
	 * whether this is a grove or an orchard.
	 */
	private static final String TAG_PARAM = "tag";
	/**
	 * The name of the property saying what kind of trees.
	 */
	private static final String KIND_PROPERTY = "kind";
	/**
	 * Constructor.
	 */
	public GroveNode() {
		super(Grove.class);
	}
	/**
	 * @param players ignored
	 * @param warner a Warning instance to use for warnings
	 * @return the Grove this represents
	 * @throws SPFormatException if missing a required property that should be generated by the factory
	 */
	@Override
	public Grove produce(final PlayerCollection players, final Warning warner) throws SPFormatException {
		return new Grove("orchard".equals(getProperty(TAG_PARAM)),
				Boolean.parseBoolean(getProperty(WILD_PARAM)),
				getProperty(KIND_PROPERTY), Long.parseLong(getProperty("id")));
	}
	/**
	 * @param property the name of a property
	 * @return whether this kind of node can use the property
	 */
	@Override
	public boolean canUse(final String property) {
		return EqualsAny.equalsAny(property, TAG_PARAM, WILD_PARAM, KIND_PROPERTY, OLD_KIND_PARAM, "id");
	}
	/**
	 * Check whether the Node's data is valid. A Grove is valid if it has no
	 * children and "tag" (should be generated by the factory, not in the XML),
	 * "wild", and "tree" properties.
	 * @param warner a Warning instance to use for warnings
	 * @throws SPFormatException if the data is invalid
	 */
	@Override
	public void checkNode(final Warning warner) throws SPFormatException {
		if (iterator().hasNext()) {
			throw new UnwantedChildException(getProperty(TAG_PARAM), iterator()
					.next().toString(), getLine());
		} else if (hasProperty(TAG_PARAM)) {
			if (hasProperty(WILD_PARAM)) {
				if (!hasProperty(KIND_PROPERTY)) {
					if (hasProperty(OLD_KIND_PARAM)) {
						warner.warn(new DeprecatedPropertyException(
								getProperty(TAG_PARAM), OLD_KIND_PARAM, KIND_PROPERTY,
								getLine()));
						addProperty(KIND_PROPERTY, getProperty(OLD_KIND_PARAM), warner);
					} else {
						throw new MissingParameterException(getProperty(TAG_PARAM),
								"kind", getLine());
					}
				}
				if (hasProperty("id")) {
					IDFactory.FACTORY.register(Long.parseLong(getProperty("id")));
				} else {
					warner.warn(new MissingParameterException(getProperty(TAG_PARAM), "id", getLine()));
					addProperty("id", Long.toString(IDFactory.FACTORY.getID()), warner);
				}
			} else {
				throw new MissingParameterException(getProperty(TAG_PARAM), WILD_PARAM,
						getLine());
			}
		} else {
			// The NodeFactory is supposed to create the 'tag' property; if it's
			// not there, something is *very* wrong.
			throw new IllegalStateException(new MissingParameterException(
					"grove or orchard", TAG_PARAM, getLine()));
		}
	}
	/**
	 * @return a String representation of the node
	 */
	@Override
	public String toString() {
		return "GroveNode";
	}
}
