package controller.map.simplexml.node;

import model.map.PlayerCollection;
import model.map.fixtures.Meadow;
import util.EqualsAny;
import util.Warning;
import controller.map.MissingParameterException;
import controller.map.SPFormatException;
import controller.map.UnwantedChildException;
import controller.map.misc.IDFactory;
/**
 * A Node to produce a Meadow.
 * @author Jonathan Lovelace
 * 
 * FIXME: Groves have "wild", meadows have "cultivated".
 *
 */
@Deprecated
public class MeadowNode extends AbstractFixtureNode<Meadow> {
	/**
	 * The name of the property saying whether or not the field or meadow is cultivated.
	 */
	private static final String CULTIVATED_PARAM = "cultivated";
	/**
	 * The name of the (factory-generated) property saying whether this is a meadow or a field. 
	 */
	private static final String TAG_PROPERTY = "tag";
	/**
	 * The name of the property saying what kind of meadow or field it is.
	 */
	private static final String KIND_PROPERTY = "kind";
	/**
	 * Constructor.
	 */
	public MeadowNode() {
		super(Meadow.class);
	}
	/**
	 * Produce the Node.
	 * @param players ignored
	 * @param warner a Warning instance to use for warnings
	 * @return the Meadow this represents
	 * @throws SPFormatException if a required attribute is missing.
	 */
	@Override
	public Meadow produce(final PlayerCollection players, final Warning warner) throws SPFormatException {
		return new Meadow(getProperty(KIND_PROPERTY),
				"field".equals(getProperty(TAG_PROPERTY)),
				Boolean.parseBoolean(getProperty(CULTIVATED_PARAM)), Long.parseLong(getProperty("id")));
	}
	/**
	 * @param property the name of a property
	 * @return whether this kind of node can use the property
	 */
	@Override
	public boolean canUse(final String property) {
		return EqualsAny.equalsAny(property, KIND_PROPERTY, TAG_PROPERTY, CULTIVATED_PARAM, "id");
	}
	
	/**
	 * Check whether the Node's data is valid. A Meadow is valid if it has no
	 * children and "tag" (should be generated by the factory, not in the XML),
	 * "kind", and "cultivated" properties.
	 * 
	 * @param warner
	 *            a Warning instance to use for warnings
	 * @throws SPFormatException
	 *             on invalid data
	 */
	@Override
	public void checkNode(final Warning warner) throws SPFormatException {
		if (iterator().hasNext()) {
			// FIXME: This should go after we've ensured that we have a 'tag'
			// property.
			throw new UnwantedChildException(getProperty(TAG_PROPERTY), iterator().next()
					.toString(), getLine());
		} else if (hasProperty(TAG_PROPERTY)) {
			if (hasProperty(CULTIVATED_PARAM)) {
				if (hasProperty(KIND_PROPERTY)) {
					if (hasProperty("id")) {
						IDFactory.FACTORY.register(Long.parseLong(getProperty("id")));
					} else {
						warner.warn(new MissingParameterException(getProperty(TAG_PROPERTY), "id", getLine()));
						addProperty("id", Long.toString(IDFactory.FACTORY.getID()), warner);
					}
				} else {
					throw new MissingParameterException(getProperty(TAG_PROPERTY), KIND_PROPERTY,
							getLine());
				}
			} else {
				throw new MissingParameterException(getProperty(TAG_PROPERTY),
						CULTIVATED_PARAM, getLine());
			}
		} else {
			// The 'tag' property is supposed to be added by the NodeFactory; if
			// it isn't present, something is *very* wrong.
			throw new IllegalStateException(new MissingParameterException(
					"meadow or field", TAG_PROPERTY, getLine()));
		}
	}
	/**
	 * @return a String representation of the Node
	 */
	@Override
	public String toString() {
		return "MeadowNode";
	}
}
